"""empty message

Revision ID: 45688474737e
Revises: cecb3a7c8deb
Create Date: 2025-07-17 16:25:35.400983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45688474737e'
down_revision = 'cecb3a7c8deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_points', sa.Integer(), nullable=True))

    with op.batch_alter_table('userpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userpoints', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('points')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('total_points')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('price')
        batch_op.drop_column('category')

    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
