"""empty message

Revision ID: 7e096f2714af
Revises: d9173c4ebba4
Create Date: 2025-07-04 22:31:20.304609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e096f2714af'
down_revision = 'd9173c4ebba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userpoints')
    op.drop_table('products')
    op.drop_table('menus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('menus_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='menus_store_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='menus_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('menu_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], name='products_menu_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    op.create_table('userpoints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='userpoints_store_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='userpoints_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='userpoints_pkey')
    )
    # ### end Alembic commands ###
